Учебный проект: вдохнуть жизнь
htmlacademy-nodejs/77390-buy-and-sell-3 pull request #11
Opened 2020-05-24 10:33 UTC by Angelpsy

2020-05-26 21:45 UTC, Krabaton requested changes
Это на первый взгляд. Слишком уж много изменений за один раз.

2020-05-26 21:45 UTC, Krabaton commented on src/express/controls/main.js
> +    const offers = await getOffers({offsetStart: 0, offsetEnd: 8})
`const { data: { items: offers }} = await getOffers({offsetStart: 0, offsetEnd: 8})`

2020-05-26 21:45 UTC, Krabaton commented on src/express/controls/main.js
> +    const discussedOffers = await getDiscussedOffers()
`const { data: { items: discussedOffers }} = await getDiscussedOffers()`

2020-05-26 21:45 UTC, Krabaton commented on src/express/controls/my.js
> +    const offers = await getOffers()
`const { data: { items: offers }} = await getOffers()`

2020-05-26 21:45 UTC, Krabaton commented on src/express/controls/offers.js
> +    await addOffer(item)
А к чему мы тут then добавляем без присваивания?

2020-05-26 21:45 UTC, Krabaton commented on src/express/routes/offers.js
> +router.get(`/add`, ctrlOfferAddGet);
Не нравится, что в имени контроллера указан глагол (GET, POST). Явно, что-то не то. Подумать как переименовать.

2020-05-26 21:45 UTC, Krabaton commented on src/express/controls/offers.js
> +  const item = {
А валидация входных данных?

2020-05-30 06:26 UTC, Angelpsy commented on src/express/controls/main.js
> +    const offers = await getOffers({offsetStart: 0, offsetEnd: 8})
не нравятся такие сложные конструкции - слишком сложны для беглого восприятия

2020-05-30 06:27 UTC, Angelpsy commented on src/express/controls/offers.js
> +  const item = {
Валидация происходит на стороне  service-server, думаю тут будет излишне

2020-05-30 11:10 UTC, merged